sudo: required
services:
  - docker
  
# create builds first
before_install:
  - docker build -t wlee88/react-test -f  ./client/Dockerfile.dev ./client
    
script:
  - docker run -e CI=true wlee88/react-test npm test

after_success:
  - docker build -t wlee88/multi-client ./client
  - docker build -t wlee88/multi-nginx ./nginx
  - docker build -t wlee88/multi-server ./server
  - docker build -t wlee88/multi-worker ./worker
    
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push to docker hub
  - docker push wlee88/multi-client
  - docker push wlee88/multi-nginx
  - docker push wlee88/multi-server
  - docker push wlee88/multi-worker
    
deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-178390946795
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY